// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/user/schema.prisma",
  migrations: {
    path: "prisma/user/migrations",
    seed: "node prisma/seed.js"
  },
  datasource: {
    url: env("BANKING_DB_URL"),
  },
});
